name: CiteCore
version: 1.0.1
authors:
  - Lenoob_
  - TitouLeVrai
main: fr.cite.core.Main
api-version: 1.19
commands:
  npc:
    description: Commande relatives au npc
    permission: core.npc.use
    permission-message: Vous n'avez pas la permission
  money:
    description: Commande relative au Drachmes
    permission: core.money.use
    permission-message: Vous n'avez pas la permission